### PR TITLE
Update unload macro

### PR DESCRIPTION
**Pull request by rgallagher27**
Add newly supported UNLOAD parameters since this macros was created. Mainly the addition of HEADER and REGION.

### CODE REVIEW

**Comment by rgallagher27** [comment]
Just fixing an issue with the `FORMAT` param. Looks like it can't be used alongside `DELIMITER` and `ESCAPE` so just fixing that atm.

**Comment by rgallagher27** [comment]
This should be good to go as of the last commit

**Comment by drewbanin** [comment]
Thanks @rgallagher27 - merging!

**Comment by abelsonlive** [comment]
woah! i was about to update this and then saw this :)

**Pull request merged**
