### PR TITLE
Renames views;  Adds Dependencies view

### PR DESCRIPTION
**Pull request by tconbeer**
```
PS C:\Users\tconb\Documents\GitHub\redshift> dbt run
Found 23 models, 0 tests, 0 archives, 0 analyses, 114 macros, 2 operations, 0 seed files

17:47:36 | Concurrency: 1 threads (target='dev')
17:47:36 |
17:47:36 | 1 of 5 START view model dbt_tconbeer_redshift_package.redshift_dependencies [RUN]
17:47:40 | 1 of 5 OK created view model dbt_tconbeer_redshift_package.redshift_dependencies [CREATE VIEW in 4.21s]
17:47:40 | 2 of 5 START view model dbt_tconbeer_redshift_package.redshift_users_schema_privileges [RUN]
17:47:45 | 2 of 5 OK created view model dbt_tconbeer_redshift_package.redshift_users_schema_privileges [CREATE VIEW in 4.43s]
17:47:45 | 3 of 5 START view model dbt_tconbeer_redshift_package.redshift_users_table_view_privileges [RUN]
17:47:49 | 3 of 5 OK created view model dbt_tconbeer_redshift_package.redshift_users_table_view_privileges [CREATE VIEW in 3.93s]
17:47:49 | 4 of 5 START view model dbt_tconbeer_redshift_package.redshift_queries [RUN]
17:47:53 | 4 of 5 OK created view model dbt_tconbeer_redshift_package.redshift_queries [CREATE VIEW in 4.29s]
17:47:53 | 5 of 5 START view model dbt_tconbeer_redshift_package.redshift_table_stats [RUN]
17:47:57 | 5 of 5 OK created view model dbt_tconbeer_redshift_package.redshift_table_stats [CREATE VIEW in 3.75s]
17:47:57 |
17:47:57 | Finished running 5 view models in 28.08s.

Completed successfully

Done. PASS=5 ERROR=0 SKIP=0 TOTAL=5
PS C:\Users\tconb\Documents\GitHub\redshift> dbt test
Found 23 models, 0 tests, 0 archives, 0 analyses, 114 macros, 2 operations, 0 seed files
WARNING: Nothing to do. Try checking your model configs and model specification args
```

### CODE REVIEW

**Comment by tconbeer** [comment]
Not sure if this is interesting to you guys, but I find myself querying dependencies when source tables change pretty regularly

**Comment by drewbanin** [comment]
Thanks for the PR @tconbeer! I'm pretty into this -- I think we should have prefixed these models from the outset. Not at all opposed to the new models either. Let me give this a spin and let you know if I have any particular feedback :)

**Comment by tconbeer** [comment]
All set. Thanks for the review, @drewbanin

**Comment by drewbanin** [comment]
Nice work @tconbeer. Just published a release including this code: https://github.com/fishtown-analytics/redshift/releases/tag/0.2.0

**Pull request merged**
